# Generated by Django 4.0.1 on 2022-02-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_status_taskhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
    ]
