# Generated by Django 4.0.1 on 2022-02-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskhistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='newstatus',
            new_name='new_status',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='oldstatus',
            new_name='old_status',
        ),
    ]
