# Generated by Django 4.0.1 on 2022-02-20 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_report_confirmation_alter_report_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Enter time in UTC format .', null=True),
        ),
    ]
