# Generated by Django 4.0.1 on 2022-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_report_confirmation_alter_report_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, help_text='I want to receive daily reports'),
        ),
    ]
