# Generated by Django 4.0.1 on 2022-02-24 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_report_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Enter time in UTC format hh:mm:ss .'),
        ),
    ]
